import Footer from "@/pages/Footer";
import "./globals.css";

import { Navbar } from "@/components";

export const metadata = {
  title: "Mobile Insight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className=" bg-[#dad5f6] text-[#030208]" lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
